export const gifts = [
  "Cama Queen",
  "Colchón para cama Queen",
  "Sofá / sillón sala",
  "Mesa de comedor + sillas (4 sillas)",
  "2 Mesas de noche",
  "Sábanas + almohadas + frazada (Cama Queen)",
  "Refrigeradora",
  "Microondas",
  "Licuadora",
  "Hervidor eléctrico",
  "Plancha de ropa + Planchador",
  "Cafetera",
  "Freidora de aire",
  "Arrocera",
  "Aspiradora",
  "Waflera",
  "Ventilador",
  "Soundbar",
  "Batidora",
  "Aspiradora de mano",
  "Vajilla + cubiertos + vasos",
  "Juego de ollas + sartén",
  "Toallas (set completo) Colores Claros",
  "Juegos de Copas",
  "Organizadores (Para Closet, Baño)",
  "Juego de Cuchillos + Tabla de Picar",
  "Tetera de aluminio + Juego de Tazas"
];
